### ISSUE TITLE
Major cleanup python bindings API and distribution

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/python-bindings#14]
Let's collect changes for the python bindings that will have an effect on the user in this issue:

- [x] switch from return by reference to return by value https://github.com/precice/precice/issues/364
- [x] put python bindings into independent repository precice/precice#512 
- [x] merge https://github.com/precice/precice/pull/576
    - [x] entirely remove deprecated `PySolverInterface` https://github.com/precice/precice/issues/265
    - [x] entirely remove deprecated `python` bindings (https://github.com/precice/precice/tree/develop/src/precice/bindings/python) https://github.com/precice/precice/pull/576
    - [x] rename `python_future` to `python` bindings (https://github.com/precice/precice/tree/develop/src/precice/bindings/python_future) https://github.com/precice/precice/pull/576
- [x] find a proper solution for shipping the bindings https://github.com/precice/precice/issues/352 precice/python-bindings#4 
- [x] single step setup https://github.com/precice/python-bindings/issues/11
